version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  client:
    build: ./client
    ports:
      - 3000:3000
    restart: always
  server1:
    build: ./server1
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongo
  server2:
    build: ./server2
    ports:
      - 5001:5001
    restart: always
    depends_on:
      - mongo
  server3:
    build: ./server3
    ports:
      - 5002:5002
    restart: always
    depends_on:
      - mongo
